# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run job 1
        run: echo $GITHUB_WORKSPACE
  job2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run job 2
        run: echo $GITHUB_WORKSPACE
  job3:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run job 3
        run: echo $GITHUB_WORKSPACE
  job4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run job 4
        run: echo $GITHUB_WORKSPACE
