# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Pythong syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
      - name: Run job 1
        run: ls $GITHUB_WORKSPACE
